@startuml

!theme plain
left to right direction
skinparam linetype ortho

class HtmlDocument {
    - idToElementMap: Map<String, HtmlElement>
    - factory: HtmlElementFactory
    - root: HtmlElement
    ---
    + ...
}
class HtmlElement {
      - tagName: String
      - children: List<HtmlNode>
      - id: String
    ---
    + ...
  + accept(HtmlVisitor): void
}
class HtmlElementFactory {
  + createElement(...): HtmlElement
}
class HtmlNode {
    - parent: HtmlElement
    ---
  + accept(HtmlVisitor): void
  + ...
}
class HtmlTextNode {
    - text: String
---
  + accept(HtmlVisitor): void
  + ...
}
'class HtmlTreePrinter {
'  + print(HtmlElement, boolean): void
'}
'interface HtmlVisitor << interface >> {
'  + visit(HtmlTextNode): void
'  + visit(HtmlElement): void
'}
'class SpellCheckUtils {
'- langTool: JLanguageTool
'  + hasErrors(String): boolean
'  + checkText(String): List<RuleMatch>
'}
'class SpellCheckVisitor {
'  + visit(HtmlElement): void
'  + visit(HtmlTextNode): void
'}
'class SpellChecker {
'  + getErrorMapAsString(HtmlElement): String
'  + getErrorMap(HtmlElement): Map<String, List<RuleMatch>>
'  + printErrorMap(HtmlElement): void
'}
'class TreePrintVisitor {
'  + visit(HtmlElement): void
'  + visit(HtmlTextNode): void
'}
'
'class PrintTreeUtils {
'+ getIndentString(Stack<Boolean>, int): String
'+ getConnectorString(boolean, int): String
'}

HtmlDocument       "1" *-[#595959,plain]-> "idToElementMap\n*" HtmlElement
HtmlDocument       "1" *-[#595959,plain]-> "factory\n1" HtmlElementFactory
HtmlDocument        -[#595959,dashed]->  HtmlElementFactory : "«create»"
HtmlElement         -[#000082,plain]-^  HtmlNode
HtmlElement        "1" *-[#595959,plain]-> "children\n*" HtmlNode
HtmlElement         -[#595959,dashed]->  HtmlTextNode       : "«create»"
HtmlElementFactory "1" *-[#595959,plain]-> "document\n1" HtmlDocument
HtmlElementFactory  -[#595959,dashed]->  HtmlElement        : "«create»"
HtmlNode           "1" *-[#595959,plain]-> "parent\n1" HtmlElement
HtmlTextNode        -[#000082,plain]-^  HtmlNode
'SpellCheckVisitor   -[#008200,dashed]-^  HtmlVisitor
'SpellChecker       "1" *-[#595959,plain]-> "visitor\n1" SpellCheckVisitor
'SpellCheckUtils        -[#000082,dashed]-   SpellCheckVisitor
'SpellCheckUtils        -[#000082,dashed]-   TreePrintVisitor
'TreePrintVisitor    -[#008200,dashed]-^  HtmlVisitor
'PrintTreeUtils      -[#000082,dashed]-   TreePrintVisitor
'HtmlTreePrinter    "1" *-[#595959,plain]-> "visitor\n1"  TreePrintVisitor
@enduml
